"""Initial migration

Revision ID: fc32bbb6d3c8
Revises: 
Create Date: 2025-08-16 17:20:58.045774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc32bbb6d3c8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_equipment_id"), "equipment", ["id"], unique=False)
    op.create_index(op.f("ix_equipment_name"), "equipment", ["name"], unique=True)
    op.create_table(
        "factories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_factories_id"), "factories", ["id"], unique=False)
    op.create_index(op.f("ix_factories_name"), "factories", ["name"], unique=True)
    op.create_table(
        "sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("factory_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["factory_id"],
            ["factories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sections_id"), "sections", ["id"], unique=False)
    op.create_index(op.f("ix_sections_name"), "sections", ["name"], unique=False)
    op.create_table(
        "section_equipment_association",
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("equipment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.PrimaryKeyConstraint("section_id", "equipment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("section_equipment_association")
    op.drop_index(op.f("ix_sections_name"), table_name="sections")
    op.drop_index(op.f("ix_sections_id"), table_name="sections")
    op.drop_table("sections")
    op.drop_index(op.f("ix_factories_name"), table_name="factories")
    op.drop_index(op.f("ix_factories_id"), table_name="factories")
    op.drop_table("factories")
    op.drop_index(op.f("ix_equipment_name"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_id"), table_name="equipment")
    op.drop_table("equipment")
    # ### end Alembic commands ###
